email:

license:

subdomain: 

auth:
  google:
    enabled: true
    clientId: 
    clientSecret: 

cluster:
  endpoint:

registry:
  storage:
    provider:
      gcp:
        enabled: true
        project:
        bucket:

buildkit:
  ingress:
    enabled: false
  service:
    type: LoadBalancer