email:

license:

subdomain: 

auth:
  google:
    enabled: true
    clientId: 
    clientSecret: 

cluster:
  endpoint:

cloud:
  provider:
    gcp:
      enabled: true
      project: 
      bucket:

buildkit:
  ingress:
    enabled: false
  service:
    type: LoadBalancer
  persistency:
    enabled: true
