[[redirects]]
  from = "/docs/getting-started/installation"
  to = "/docs/cloud/okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/enterprise/*"
  to = "/docs/self-hosted/:splat"
  status = 301

# Redirect the current version to /docs/
[[redirects]]
  from = "/docs/1.8/*"
  to = "/docs/:splat"
  status = 301

# Before version 1.4, we used to point the homepage to `/welcome/overview`.
# These redirects make sure we donâ€™t show a 404

[[redirects]]
  from = "/docs/welcome/overview/"
  to = "/docs/"
  status = 301

[[redirects]]
  from = "/docs/1.3/welcome/overview/"
  to = "/docs/1.3"
  status = 301

[[redirects]]
  from = "/docs/1.2/welcome/overview/"
  to = "/docs/1.2"
  status = 301

[[redirects]]
  from = "/docs/1.1/welcome/overview/"
  to = "/docs/1.1"
  status = 301

[[redirects]]
  from = "/docs/1.0/welcome/overview/"
  to = "/docs/1.0"
  status = 301

[[redirects]]
  from = "/docs/0.15/welcome/overview/"
  to = "/docs/0.15"
  status = 301

[[redirects]]
  from = "/docs/0.14/welcome/overview/"
  to = "/docs/0.14"
  status = 301

[[redirects]]
  from = "/docs/0.14/welcome/overview/"
  to = "/docs/0.13"
  status = 301

[[redirects]]
  from = "/docs/0.12/welcome/overview/"
  to = "/docs/0.12"
  status = 301

[[redirects]]
  from = "/docs/0.11/welcome/overview/"
  to = "/docs/0.11"
  status = 301

[[redirects]]
  from = "/"
  to = "/docs"
  status = 301

[[redirects]]
  from = "/*"
  to = "/docs/404.html"
  status = 404

[build]
  functions = "netlify/functions"

[[headers]]
  for = "/**/*.yaml"
  [headers.values]
    Content-Type = "text/plain"