[[redirects]]
  from = "/docs/cloud/private-repositories"
  to = "/docs/deploy/private-repositories"
  status = 301

[[redirects]]
  from = "/docs/cloud/develop-on-okteto-button"
  to = "/docs/deploy/develop-on-okteto-button"
  status = 301

[[redirects]]
  from = "/docs/cloud/okteto-pipeline"
  to = "/docs/deploy/okteto-pipeline"
  status = 301

[[redirects]]
  from = "/docs/cloud/github-actions"
  to = "/docs/reference/supported-github-actions"
  status = 301

[[redirects]]
  from = "/docs/cloud/github-actions"
  to = "/docs/reference/supported-github-actions"
  status = 301

[[redirects]]
  from = "/docs/okteto-pipline"
  to = "/docs/deploy/okteto-pipeline"
  status = 301

[[redirects]]
  from = "/docs/reference/cli"
  to = "/docs/reference/okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/reference/manifest"
  to = "/docs/reference/okteto-manifest"
  status = 301

[[redirects]]
  from = "/docs/reference/compose"
  to = "/docs/reference/docker-compose"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/overview"
  to = "/docs/self-hosted/overview-self-hosted"
  status = 301

[[redirects]]
  from = "/docs/self-hosted"
  to = "/docs/self-hosted/overview-self-hosted"
  status = 301

[[redirects]]
  from = "/docs/administration/okteto-license"
  to = "/docs/self-hosted/manage/okteto-license"
  status = 301

[[redirects]]
  from = "/docs/administration/*"
  to = "/docs/self-hosted/admin/:splat"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/releases"
  to = "/docs/release-notes"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/*"
  to = "/docs/self-hosted/manage/:splat"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/administration/configuration"
  to = "/docs/reference/helm-chart-values"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/administration/*"
  to = "/docs/self-hosted/install/:splat"
  status = 301

[[redirects]]
  from = "/docs/administration/private-repositories/*"
  to = "/docs/self-hosted/install/private-repositories/:splat"
  status = 301

[[redirects]]
  from = "/docs/cloud/preview-environments/preview-environments"
  to = "/docs/preview/overview-prev-env"
  status = 301

[[redirects]]
  from = "/docs/cloud/preview-environments/dashboard"
  to = "/docs/preview/github/configure-github-prev"
  status = 301

[[redirects]]
  from = "/docs/cloud/preview-environments/preview-environments-github"
  to = "/docs/preview/github/using-github-actions"
  status = 301

[[redirects]]
  from = "/docs/cloud/preview-environments/preview-environments-gitlab"
  to = "/docs/preview/using-gitlab-cicd"
  status = 301

[[redirects]]
  from = "/docs/reference/development-environments"
  to = "/docs/deploy/development-environments"
  status = 301

[[redirects]]
  from = "/docs/cloud/deploy-from-git"
  to = "/docs/deploy/deploy-from-git"
  status = 301

[[redirects]]
  from = "/docs/cloud/launch-from-catalog"
  to = "/docs/deploy/launch-from-catalog"
  status = 301

[[redirects]]
  from = "/docs/tutorials/*"
  to = "/docs/guides/tutorials/:splat"
  status = 301

[[redirects]]
  from = "/docs/cloud/secrets"
  to = "/docs/manifest/okteto-secrets"
  status = 301

[[redirects]]
  from = "/docs/cloud/external-resources"
  to = "/docs/manifest/external-resources"
  status = 301

[[redirects]]
  from = "/docs/cloud/build"
  to = "/docs/core/components/build-service"
  status = 301

[[redirects]]
  from = "/docs/cloud/registry"
  to = "/docs/core/components/container-registry"
  status = 301

[[redirects]]
  from = "/docs/cloud/namespaces"
  to = "/docs/core/components/namespaces"
  status = 301

[[redirects]]
  from = "/docs/cloud/use-volume-snapshots"
  to = "/docs/core/components/use-volume-snapshots"
  status = 301

[[redirects]]
  from = "/docs/cloud/ssl"
  to = "/docs/core/ingress/automatic-ssl"
  status = 301

[[redirects]]
  from = "/docs/cloud/private-endpoints"
  to = "/docs/core/ingress/private-endpoints"
  status = 301

[[redirects]]
  from = "/docs/cloud/credentials"
  to = "/docs/core/credentials/kubernetes-credentials"
  status = 301

[[redirects]]
  from = "/docs/cloud/personal-access-tokens"
  to = "/docs/core/credentials/personal-access-tokens"
  status = 301

[[redirects]]
  from = "/docs/cloud/okteto-cli"
  to = "/docs/core/using-okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/eks"
  to = "/docs/get-started/cloud-provider-guides/amazon-eks"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/aks"
  to = "/docs/get-started/cloud-provider-guides/microsoft-aks"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/civo"
  to = "/docs/get-started/cloud-provider-guides/civo"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/do"
  to = "/docs/get-started/cloud-provider-guides/digitalocean-doks"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/gke"
  to = "/docs/get-started/cloud-provider-guides/google-gke"
  status = 301

[[redirects]]
  from = "/docs/using-dev-envs"
  to = "/docs/get-started/deploy-first-environment"
  status = 301

[[redirects]]
  from = "/docs/getting-started"
  to = "/docs/get-started/install-okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/preparation"
  to = "/docs/get-started/preparation"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/deployment"
  to = "/docs/get-started/quickstart-guide"
  status = 301

[[redirects]]
  from = "/docs/getting-started/installation"
  to = "/docs/cloud/okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/administration/dashboard"
  to = "/docs/admin/dashboard"
  status = 301

[[redirects]]
  from = "/docs/administration/catalog"
  to = "/docs/admin/catalog"
  status = 301

[[redirects]]
  from = "/docs/administration/cleanup"
  to = "/docs/admin/cleanup"
  status = 301

[[redirects]]
  from = "/docs/administration/okteto-insights"
  to = "/docs/admin/okteto-insights"
  status = 301

[[redirects]]
  from = "/docs/enterprise/*"
  to = "/docs/self-hosted/:splat"
  status = 301

# Redirect the current version to /docs/
[[redirects]]
  from = "/docs/1.15/*"
  to = "/docs/:splat"
  status = 301

# Before version 1.4, we used to point the homepage to `/welcome/overview`.
# These redirects make sure we donâ€™t show a 404

[[redirects]]
  from = "/docs/1.3/*"
  to = "/docs/:splat"
  status = 301

[[redirects]]
  from = "/docs/1.2/*"
  to = "/docs/:splat"
  status = 301

[[redirects]]
  from = "/docs/1.1/*"
  to = "/docs/:splat"
  status = 301

[[redirects]]
  from = "/docs/1.0/*"
  to = "/docs/:splat"
  status = 301

[[redirects]]
  from = "/docs/0.15/*"
  to = "/docs/:splat"
  status = 301

[[redirects]]
  from = "/docs/0.14/*"
  to = "/docs/:splat"
  status = 301

[[redirects]]
  from = "/docs/0.12/*"
  to = "/docs/:splat"
  status = 301

[[redirects]]
  from = "/docs/0.11/*"
  to = "/docs/:splat"
  status = 301

[[redirects]]
  from = "/docs/welcome/overview/"
  to = "/docs/"
  status = 301

[[redirects]]
  from = "/"
  to = "/docs"
  status = 301

[[redirects]]
  from = "/*"
  to = "/docs/404.html"
  status = 404

[build]
  functions = "netlify/functions"