[[redirects]]
  from = "/docs/self-hosted/install/private-repositories/*"
  to = "/docs/admin/private-repositories/:splat"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/custom-installer-image"
  to = "/docs/admin/custom-installer-image"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/argocd"
  to = "/docs/self-hosted/manage/argocd"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/guides/azure-active-directory"
  to = "/docs/self-hosted/install/auth/azure-ad"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/guides/gitlab"
  to = "/docs/self-hosted/install/auth/gitlab"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/guides/okta"
  to = "/docs/self-hosted/install/auth/okta"
  status = 301

[[redirects]]
  from = "/docs/get-started/overview"
  to = "/docs/get-started/install"
  status = 301

[[redirects]]
  from = "/docs/get-started/cloud-provider-guides/*"
  to = "/docs/get-started/install/:splat"
  status = 301

[[redirects]]
  from = "/docs/core/components/build-service"
  to = "/docs/core/build-service"
  status = 301

[[redirects]]
  from = "/docs/core/components/container-registry"
  to = "/docs/core/container-registry"
  status = 301

[[redirects]]
  from = "/docs/core/components/development-containers"
  to = "/docs/development/containers/hybrid"
  status = 301

[[redirects]]
  from = "/docs/core/components/namespaces"
  to = "/docs/core/namespaces"
  status = 301

[[redirects]]
  from = "/docs/core/ingress/*"
  to = "/docs/core/endpoints/:splat"
  status = 301

[[redirects]]
  from = "/docs/core/using-okteto-cli"
  to = "/docs/development/using-okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/manifest/hybrid-development"
  to = "/docs/development/containers/hybrid"
  status = 301

[[redirects]]
  from = "/docs/manifest/okteto-variables"
  to = "/docs/core/okteto-variables"
  status = 301

[[redirects]]
  from = "/docs/manifest/overview-manifest"
  to = "/docs/core/okteto-manifest"
  status = 301

[[redirects]]
  from = "/docs/manifest/external-resources"
  to = "/docs/tutorials/external-resources"
  status = 301

[[redirects]]
  from = "/docs/deploy/development-environments"
  to = "/docs/development/images"
  status = 301

[[redirects]]
  from = "/docs/deploy/*"
  to = "/docs/development/deploy/:splat"
  status = 301

[[redirects]]
  from = "/docs/deploy/development-containers/*"
  to = "/docs/development/containers/:splat"
  status = 301

[[redirects]]
  from = "/docs/guides/tutorials/*"
  to = "/docs/tutorials/:splat"
  status = 301

[[redirects]]
  from = "/docs/tutorials/stacks-getting-started"
  to = "/docs/tutorials/compose-getting-started"
  status = 301


[[redirects]]
  from = "/docs/guides/samples/more"
  to = "/docs/development/containers/file-sync"
  status = 301

[[redirects]]
  from = "/docs/guides/samples/*"
  to = "/docs/development/containers/file-sync/:splat"
  status = 301

[[redirects]]
  from = "/docs/preview/overview-prev-env"
  to = "/docs/previews"
  status = 301

[[redirects]]
  from = "/docs/preview/github/using-github-actions"
  to = "/docs/previews/using-github-actions"
  status = 301

[[redirects]]
  from = "/docs/preview/using-gitlab-cicd"
  to = "/docs/previews/using-gitlab-cicd"
  status = 301

[[redirects]]
  from = "/docs/reference/helm-chart-values"
  to = "/docs/self-hosted/helm-configuration"
  status = 301

[[redirects]]
  from = "/docs/get-started/deploy-first-environment"
  to = "/docs/get-started/deploy-your-app"
  status = 301

[[redirects]]
  from = "/docs/cloud/private-repositories"
  to = "/docs/development/deploy/from-private-repositories"
  status = 301

[[redirects]]
  from = "/docs/cloud/develop-on-okteto-button"
  to = "/docs/development/deploy/develop-on-okteto-button"
  status = 301

[[redirects]]
  from = "/docs/cloud/okteto-pipeline"
  to = "/docs/manifest/overview-manifest"
  status = 301

[[redirects]]
  from = "/docs/guides/tutorials/getting-started-with-pipelines"
  to = "/docs/tutorials/getting-started-with-okteto"
  status = 301

[[redirects]]
  from = "/docs/cloud/github-actions"
  to = "/docs/reference/supported-github-actions"
  status = 301

[[redirects]]
  from = "/docs/okteto-pipeline"
  to = "/docs/manifest/overview-manifest"
  status = 301

[[redirects]]
  from = "/docs/reference/cli"
  to = "/docs/reference/okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/reference/manifest"
  to = "/docs/reference/okteto-manifest"
  status = 301

[[redirects]]
  from = "/docs/1.16/reference/manifest"
  to = "/docs/1.16/reference/okteto-manifest"
  status = 301

[[redirects]]
  from = "/docs/1.17/reference/manifest"
  to = "/docs/1.17/reference/okteto-manifest"
  status = 301

[[redirects]]
  from = "/docs/reference/compose"
  to = "/docs/reference/docker-compose"
  status = 301

[[redirects]]
  from = "/docs/reference/stacks"
  to = "/docs/reference/docker-compose"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/overview"
  to = "/docs/self-hosted"
  status = 301

[[redirects]]
  from = "/docs/administration/okteto-license"
  to = "/docs/self-hosted/manage/okteto-license"
  status = 301

[[redirects]]
  from = "/docs/administration/*"
  to = "/docs/admin/:splat"
  status = 301

[[redirects]]
  from = "/docs/1.16/administration/*"
  to = "/docs/1.16/admin/:splat"
  status = 301

[[redirects]]
  from = "/docs/1.17/administration/*"
  to = "/docs/1.17/admin/:splat"
  status = 301


[[redirects]]
  from = "/docs/self-hosted/install/releases"
  to = "/docs/release-notes"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/backup"
  to = "/docs/self-hosted/manage/backup"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/upgrade"
  to = "/docs/self-hosted/manage/upgrade"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/custom-resource-definitions"
  to = "/docs/self-hosted/manage/custom-resource-definitions"
  status = 301

[[redirects]]
  from = "/docs/1.16/self-hosted/install/custom-resource-definitions"
  to = "/docs/1.16/self-hosted/manage/custom-resource-definitions"
  status = 301

[[redirects]]
  from = "/docs/1.17/self-hosted/install/custom-resource-definitions"
  to = "/docs/1.17/self-hosted/manage/custom-resource-definitions"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/troubleshooting"
  to = "/docs/self-hosted/manage/troubleshooting"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/administration/configuration"
  to = "/docs/reference/helm-chart-values"
  status = 301

[[redirects]]
  from = "/docs/1.16/self-hosted/administration/configuration"
  to = "/docs/1.16/reference/helm-chart-values"
  status = 301

[[redirects]]
  from = "/docs/1.17/self-hosted/administration/configuration"
  to = "/docs/1.17/reference/helm-chart-values"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/administration/*"
  to = "/docs/self-hosted/install/:splat"
  status = 301

[[redirects]]
  from = "/docs/1.16/self-hosted/administration/*"
  to = "/docs/1.16/self-hosted/install/:splat"
  status = 301

[[redirects]]
  from = "/docs/1.17/self-hosted/administration/*"
  to = "/docs/1.17/self-hosted/install/:splat"
  status = 301

[[redirects]]
  from = "/docs/administration/private-repositories/*"
  to = "/docs/self-hosted/install/private-repositories/:splat"
  status = 301

[[redirects]]
  from = "/docs/cloud/preview-environments/preview-environments"
  to = "/docs/previews"
  status = 301

[[redirects]]
  from = "/docs/1.16/cloud/preview-environments/preview-environments"
  to = "/docs/1.16/preview/overview-prev-env"
  status = 301

[[redirects]]
  from = "/docs/1.17/cloud/preview-environments/preview-environments"
  to = "/docs/1.17/preview/overview-prev-env"
  status = 301

[[redirects]]
  from = "/docs/cloud/preview-environments/preview-environments-github"
  to = "/docs/preview/github/using-github-actions"
  status = 301

[[redirects]]
  from = "/docs/cloud/preview-environments/preview-environments-gitlab"
  to = "/docs/preview/using-gitlab-cicd"
  status = 301

[[redirects]]
  from = "/docs/1.16/cloud/preview-environments/preview-environments-gitlab"
  to = "/docs/1.16/preview/using-gitlab-cicd"
  status = 301

[[redirects]]
  from = "/docs/1.17/cloud/preview-environments/preview-environments-gitlab"
  to = "/docs/1.17/preview/using-gitlab-cicd"
  status = 301

[[redirects]]
  from = "/docs/reference/development-environments"
  to = "/docs/deploy/development-environments"
  status = 301

[[redirects]]
  from = "/docs/1.16/reference/development-environments"
  to = "/docs/1.16/deploy/development-environments"
  status = 301

[[redirects]]
  from = "/docs/1.17/reference/development-environments"
  to = "/docs/1.17/deploy/development-environments"
  status = 301

[[redirects]]
  from = "/docs/cloud/deploy-from-git"
  to = "/docs/deploy/deploy-from-git"
  status = 301

[[redirects]]
  from = "/docs/cloud/launch-from-catalog"
  to = "/docs/deploy/deploy-from-catalog"
  status = 301

[[redirects]]
  from = "/docs/deploy/launch-from-catalog"
  to = "/docs/deploy/deploy-from-catalog"
  status = 301

[[redirects]]
  from = "/docs/deploy/launch-from-catalog"
  to = "/docs/development/deploy/deploy-from-catalog"
  status = 301

[[redirects]]
  from = "/docs/cloud/secrets"
  to = "/docs/core/okteto-variables"
  status = 301

[[redirects]]
  from = "/docs/1.16/cloud/secrets"
  to = "/docs/1.16/manifest/okteto-variables"
  status = 301

[[redirects]]
  from = "/docs/1.17/cloud/secrets"
  to = "/docs/1.17/manifest/okteto-variables"
  status = 301

[[redirects]]
  from = "/docs/manifest/okteto-secrets"
  to = "/docs/core/okteto-variables"
  status = 301

[[redirects]]
  from = "/docs/cloud/external-resources"
  to = "/docs/tutorials/external-resources"
  status = 301

[[redirects]]
  from = "/docs/cloud/build"
  to = "/docs/core/build-service"
  status = 301

[[redirects]]
  from = "/docs/cloud/registry"
  to = "/docs/core/container-registry"
  status = 301

[[redirects]]
  from = "/docs/cloud/namespaces"
  to = "/docs/core/namespaces"
  status = 301

[[redirects]]
  from = "/docs/1.16/cloud/namespaces"
  to = "/docs/1.16/core/components/namespaces"
  status = 301

[[redirects]]
  from = "/docs/1.17/cloud/namespaces"
  to = "/docs/1.17/core/components/namespaces"
  status = 301

[[redirects]]
  from = "/docs/cloud/use-volume-snapshots"
  to = "/docs/core/volume-snapshots"
  status = 301

[[redirects]]
  from = "/docs/cloud/ssl"
  to = "/docs/core/endpoints/automatic-ssl"
  status = 301

[[redirects]]
  from = "/docs/cloud/private-endpoints"
  to = "/docs/core/endpoints/private-endpoints"
  status = 301

[[redirects]]
  from = "/docs/cloud/credentials"
  to = "/docs/core/credentials/kubernetes-credentials"
  status = 301

[[redirects]]
  from = "/docs/1.16/cloud/credentials"
  to = "/docs/1.16/core/credentials/kubernetes-credentials"
  status = 301

[[redirects]]
  from = "/docs/1.17/cloud/credentials"
  to = "/docs/1.17/core/credentials/kubernetes-credentials"
  status = 301

[[redirects]]
  from = "/docs/cloud/personal-access-tokens"
  to = "/docs/core/credentials/personal-access-tokens"
  status = 301

[[redirects]]
  from = "/docs/cloud/okteto-cli"
  to = "/docs/development/using-okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/1.16/cloud/okteto-cli"
  to = "/docs/1.16/core/using-okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/1.17/cloud/okteto-cli"
  to = "/docs/1.17/core/using-okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/eks"
  to = "/docs/get-started/install/eks"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/aks"
  to = "/docs/get-started/install/aks"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/civo"
  to = "/docs/get-started/install/civo"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/do"
  to = "/docs/get-started/install/doks"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/gke"
  to = "/docs/get-started/install/gke"
  status = 301

[[redirects]]
  from = "/docs/using-dev-envs"
  to = "/docs/get-started/deploy-your-app"
  status = 301

[[redirects]]
  from = "/docs/getting-started"
  to = "/docs/get-started/install-okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/1.16/getting-started"
  to = "/docs/1.16/get-started/install-okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/1.17/getting-started"
  to = "/docs/1.17/get-started/install-okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/preparation"
  to = "/docs/get-started/install"
  status = 301
[[redirects]]
  from = "/docs/get-started/preparation"
  to = "/docs/get-started/install"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/overview-self-hosted"
  to = "/docs/get-started/install"
  status = 301

[[redirects]]
  from = "/docs/self-hosted/install/deployment"
  to = "/docs/get-started/install"
  status = 301

[[redirects]]
  from = "/docs/getting-started/installation"
  to = "/docs/development/using-okteto-cli"
  status = 301

[[redirects]]
  from = "/docs/enterprise/administration/*"
  to = "/docs/admin/:splat"
  status = 301

[[redirects]]
  from = "/docs/enterprise/*"
  to = "/docs/self-hosted/:splat"
  status = 301

[[redirects]]
  from = "/docs/samples/*"
  to = "/docs/development/containers/file-sync/:splat"
  status = 301

# Redirect official version to docs root
[[redirects]]
  from = "/docs/1.19/*"
  to = "/docs/:splat"
  status = 301

# Redirect unreleased to "current" version
[[redirects]]
  from = "/docs/unreleased/*"
  to = "/docs/1.20/:splat"
  status = 302

[[redirects]]
  from = "/docs/welcome/overview/"
  to = "/docs/"
  status = 301

[[redirects]]
  from = "/"
  to = "/docs"
  status = 301

[[redirects]]
  from = "/*"
  to = "/docs/404.html"
  status = 404

[build]
  functions = "netlify/functions"
