email: 

license: 

subdomain: 

auth:
  openid:
    enabled: true
    endpoints:
       issuer:
       authorization:
    clientId:
    clientSecret:

cluster:
  endpoint:

registry:
  storage:
    filesystem:
      enabled: true

cloud:
  provider:
    digitalocean:
      enabled: true

buildkit:
  ingress:
    enabled: false
  service:
    type: LoadBalancer
  persistency:
    enabled: true
