email: 

license: 

subdomain: 

auth:
  github:
    enabled: true
    clientId: 
    clientSecret:
    organization:

cluster:
  endpoint:

cloud:
  provider:
    aws:
      enabled: true
      region:
      bucket:
      iam:
        enabled: true
        accessKeyID:

buildkit:
  ingress:
    enabled: false
  service:
    type: LoadBalancer
  persistency:
    enabled: true
