email: 

license: 

subdomain: 

auth:
  github:
    enabled: true
    clientId: 
    clientSecret:
    organization:

cloud:
  provider:
    civo:
      enabled: true

registry:
  storage:
    filesystem:
      enabled: true
      persistence:
        size: 100Gi

buildkit:
  persistency:
    enabled: true
