email: 

license: 

subdomain: 

auth:
  github:
    enabled: true
    clientId: 
    clientSecret:
    organization:

cluster:
  endpoint:

cloud:
  provider:
    azure:
      enabled: true
      storage:
        container: ""
        accountName: ""

buildkit:
  ingress:
    enabled: false
  service:
    type: LoadBalancer
  persistency:
    enabled: true
